# Generated by Django 3.0.8 on 2020-07-15 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('dateNaissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DateSpectacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EndroitVille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('NbreEtoile', models.IntegerField()),
                ('endroitVille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.EndroitVille')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Spectacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('endroitVille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.EndroitVille')),
            ],
        ),
        migrations.CreateModel(
            name='SalleDeroulementSpectacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Salle')),
                ('spectacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Spectacle')),
            ],
        ),
        migrations.CreateModel(
            name='ResevationSpectarcle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spectacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Spectacle')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateDebut', models.CharField(max_length=50)),
                ('DateFin', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.CharField(max_length=20)),
                ('nbrPlace', models.IntegerField()),
                ('spectacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Spectacle')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PlaceCat')),
            ],
        ),
        migrations.AddField(
            model_name='endroitville',
            name='Ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Ville'),
        ),
        migrations.CreateModel(
            name='DepenseClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Client')),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Depense')),
            ],
        ),
        migrations.CreateModel(
            name='DateDeroulementSpectacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSpectacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.DateSpectacle')),
                ('spectacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Spectacle')),
            ],
        ),
        migrations.CreateModel(
            name='ChambreCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chambreCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ChambreCat')),
            ],
        ),
    ]
